services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - crawlnet

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - crawlnet
    volumes:
      - ./worker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  producer:
    build: ./producer
    volumes:
      - ./producer/urls.txt:/app/urls.txt
    depends_on:
      - redis
    networks:
      - crawlnet

  consumer:
    build: ./worker
    command: python /app/worker.py
    depends_on:
      - redis
      - mongodb 
    networks:
      - crawlnet
    deploy:
      replicas: 5

networks:
  crawlnet:
    external: true
